import type React from "react";

/** Shared styles for the theme builder window. Every color comes from the theme itself. */
export const s: Record<string, React.CSSProperties> = {
  window: {
    display: "flex",
    flexDirection: "column",
    height: "100vh",
    width: "100vw",
    overflow: "hidden",
    background: "var(--bg-app)",
    color: "var(--text-primary)",
    fontSize: 13,
  },
  titlebar: {
    height: 34,
    minHeight: 34,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderBottom: "1px solid var(--border)",
    userSelect: "none",
  },
  titleText: { fontSize: 13, fontWeight: 700, letterSpacing: "0.01em", pointerEvents: "none" },
  columns: { flex: 1, minHeight: 0, display: "flex" },

  // Theme list
  list: {
    width: 200,
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    borderRight: "1px solid var(--border)",
    background: "var(--bg-surface)",
  },
  listBody: { flex: 1, minHeight: 0, overflow: "auto", padding: "8px 4px", display: "flex", flexDirection: "column", gap: 1 },
  listLabel: {
    fontSize: 10,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    color: "var(--text-secondary)",
    padding: "8px 8px 4px",
  },
  themeRow: {
    height: 28,
    minHeight: 28,
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "0 8px",
    borderRadius: 9,
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 500,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    transition: "background 100ms ease",
  },
  listFooter: { padding: 8, display: "flex", flexDirection: "column", gap: 6, borderTop: "1px solid var(--border)" },

  // Settings
  main: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column" },
  mainHeader: { padding: "12px 16px", display: "flex", flexDirection: "column", gap: 8, borderBottom: "1px solid var(--border)" },
  note: { fontSize: 11, color: "var(--text-dim)", lineHeight: 1.4 },
  mainBody: { flex: 1, minHeight: 0, overflow: "auto", padding: "4px 16px 24px" },
  groupLabel: {
    fontSize: 10,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    color: "var(--text-secondary)",
    padding: "16px 0 6px",
  },
  row: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    minHeight: 34,
    padding: "4px 0",
    borderBottom: "1px solid var(--border)",
  },
  rowText: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", gap: 2 },
  rowLabel: { fontSize: 12, fontWeight: 600 },
  rowHint: { fontSize: 11, color: "var(--text-dim)", lineHeight: 1.35 },
  control: { display: "flex", alignItems: "center", gap: 6, flexShrink: 0 },
  empty: { padding: "24px 0", fontSize: 12, color: "var(--text-dim)" },

  // Inputs
  input: {
    fontFamily: "inherit",
    fontSize: 12,
    padding: "4px 7px",
    height: 24,
    borderRadius: 6,
    border: "1px solid var(--border-subtle)",
    background: "var(--bg-input)",
    color: "var(--text-primary)",
    outline: "none",
    boxSizing: "border-box",
  },
  button: {
    fontFamily: "inherit",
    fontSize: 12,
    fontWeight: 500,
    height: 26,
    padding: "0 10px",
    borderRadius: 6,
    border: "1px solid var(--border-subtle)",
    background: "var(--bg-input)",
    color: "var(--text-primary)",
    cursor: "pointer",
  },
  iconButton: {
    width: 20,
    height: 20,
    padding: 0,
    border: "none",
    borderRadius: 4,
    background: "transparent",
    color: "var(--text-dim)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  swatch: {
    position: "relative",
    width: 26,
    height: 20,
    borderRadius: 5,
    overflow: "hidden",
    border: "1px solid var(--border-subtle)",
    flexShrink: 0,
    cursor: "pointer",
    // Checkerboard so transparency is visible under the color.
    backgroundImage:
      "linear-gradient(45deg, #808080 25%, transparent 25%), linear-gradient(-45deg, #808080 25%, transparent 25%), linear-gradient(45deg, transparent 75%, #808080 75%), linear-gradient(-45deg, transparent 75%, #808080 75%)",
    backgroundSize: "8px 8px",
    backgroundPosition: "0 0, 0 4px, 4px -4px, -4px 0",
    backgroundColor: "#c0c0c0",
  },
  segment: { display: "flex", padding: 2, gap: 2, borderRadius: 7, background: "var(--bg-input)", border: "1px solid var(--border-subtle)" },
  segmentBtn: {
    fontFamily: "inherit",
    fontSize: 12,
    fontWeight: 500,
    height: 20,
    padding: "0 10px",
    border: "none",
    borderRadius: 5,
    cursor: "pointer",
  },
  switch: {
    width: 32,
    height: 18,
    borderRadius: 9,
    border: "1px solid var(--border-subtle)",
    padding: 1,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    transition: "background 160ms ease",
  },
  switchThumb: {
    width: 14,
    height: 14,
    borderRadius: "50%",
    background: "var(--text-primary)",
    transition: "transform 160ms ease",
    display: "block",
  },
};
